// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore This file is generated by OpenNext during preview/deploy builds.
import worker from "./.open-next/worker.js";
import { TestEventsDurableObject } from "./lib/test-events-do";

export { TestEventsDurableObject };

const workerHandler = worker as ExportedHandler<CloudflareEnv>;

async function handleScheduled(controller: ScheduledController) {
  console.log("Cron trigger completed", {
    cron: controller.cron,
    scheduledTime: new Date(controller.scheduledTime).toISOString(),
  });
}

export default {
  ...workerHandler,
  async scheduled(controller, _env, ctx) {
    ctx.waitUntil(handleScheduled(controller));
  },
} satisfies ExportedHandler<CloudflareEnv>;
