// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore This file is generated by OpenNext during preview/deploy builds.
import worker from "./.open-next/worker.js";
import { TestEventsDurableObject } from "./lib/test-events-do";

export { TestEventsDurableObject };
export default worker;
