// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore This file is generated by OpenNext during preview/deploy builds.
import worker from "./.open-next/worker.js";
import { deleteVoiceCloneObjects } from "./server/storage/delete-voice-clone-objects";
import { VoiceCloneEventsDurableObject } from "./server/events/voice-clone-events-do";
import {
  deleteVoiceCloneRecords,
  getStaleVoiceClones,
} from "./server/repositories/voice-clones";

export { VoiceCloneEventsDurableObject };

const workerHandler = worker as ExportedHandler<CloudflareEnv>;
const THREE_DAYS_IN_MS = 3 * 24 * 60 * 60 * 1000;

async function handleScheduled(
  controller: ScheduledController,
  env: CloudflareEnv,
) {
  const cutoff = new Date(controller.scheduledTime - THREE_DAYS_IN_MS);
  const staleVoiceClones = await getStaleVoiceClones(env.voice_clone, cutoff);

  await deleteVoiceCloneObjects(env.recordings, staleVoiceClones);
  await deleteVoiceCloneRecords(env.voice_clone, staleVoiceClones);

  console.log("Cron trigger completed", {
    cron: controller.cron,
    deletedCount: staleVoiceClones.length,
    scheduledTime: new Date(controller.scheduledTime).toISOString(),
    staleBefore: cutoff.toISOString(),
  });
}

export default {
  ...workerHandler,
  async scheduled(controller, env, ctx) {
    ctx.waitUntil(handleScheduled(controller, env));
  },
} satisfies ExportedHandler<CloudflareEnv>;
